default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: hello_rails_react
  username: sebastianhm
  password: sehemu
  host: localhost
  port: 5432

test:
  <<: *default
  database: hello_rails_react_test
  username: sebastianhm
  password: sehemu

production:
  <<: *default
  database: hello_rail_react_production
  username: hello_rails_react
  password: <%= ENV["HELLO_RAILS_REACT_DATABASE_PASSWORD"] %>