Message.create(message: 'Hello world!')
Message.create(message: 'Welcome to our community!')
Message.create(message: 'Hello and thank you for joining!')
Message.create(message: 'Greetings! Were glad youre here.')
Message.create(message: 'Hi there! Welcome to the platform.')